- name: Deploy LMS Frontend to Kubernetes
  hosts: n1
  tasks:
    - name: Apply LMS Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: lms-fe
            namespace: lms
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: lms-fe
            template:
              metadata:
                labels:
                  app: lms-fe
              spec:
                serviceAccountName: web-sa
                containers:
                  - name: frontend-container
                    image: vishruth04/fe
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 80
                    envFrom:
                      - ConfigmapRef:
                        name: frontend-config-map

    - name: Apply LMS Frontend Service
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: v1
          kind: Service
          metadata:
            name: lms-fe-service
            namespace: lms
          spec:
            type: LoadBalancer
            ports:
              - port: 80
                targetPort: 80
            selector:
              app: lms-fe
