---
- name: Create DB Secret in Kubernetes
  hosts: n1  # Ensure the target machine is correct
  become: false
  gather_facts: false
  collections:
    - kubernetes.core  # Ensure kubernetes.core is included

  tasks:
    - name: Create PostgreSQL Secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: postgres-secret
            namespace: lms
          type: Opaque
          data:
            password: "{{ 'admin12345' | b64encode }}"  # Make sure password is correctly base64 encoded
