---
- name: Create namespace and service accounts using k8s module
  hosts: n1
  become: false
  gather_facts: false

  vars:
    namespace: lms
    service_accounts:
      - db-sa
      - app-sa
      - web-sa

  tasks:
    - name: Create LMS namespace if not exists
      k8s:
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        state: present

    - name: Create service accounts in namespace
      k8s:
        api_version: v1
        kind: ServiceAccount
        namespace: "{{ namespace }}"
        name: "{{ item }}"
        state: present
      loop: "{{ service_accounts }}"

